### ISSUE TITLE
При попытке скачать данные с Binance с 2017 года

### ISSUE THREAD

**Issue by yanis7774** [AlexWan/OsEngine#79]
03.03.2019 19:36:36	Error	System.NullReferenceException: Object reference not set to an instance of an object.
   at OsEngine.Market.Servers.Binance.BinanceServerRealization.GetCandleDataToSecurity(Security security, TimeFrameBuilder timeFrameBuilder, DateTime startTime, DateTime endTime, DateTime actualTime) in \\Mac\Home\Desktop\DAHF\OsEngine-master_github\OsEngine-master\project\OsEngine\Market\Servers\Binance\BinanceServer.cs:line 180
   at OsEngine.Market.Servers.AServer.GetCandleDataToSecurity(String namePaper, TimeFrameBuilder timeFrameBuilder, DateTime startTime, DateTime endTime, DateTime actualTime, Boolean neadToUpdate) in \\Mac\Home\Desktop\DAHF\OsEngine-master_github\OsEngine-master\project\OsEngine\Market\Servers\AServer.cs:line 1223
   at OsEngine.OsData.OsDataSet.StartThis(SecurityToLoad loadSec, TimeFrame timeFrame) in \\Mac\Home\Desktop\DAHF\OsEngine-master_github\OsEngine-master\project\OsEngine\OsData\OsDataSet.cs:line 851
   at OsEngine.OsData.OsDataSet.StartSets() in \\Mac\Home\Desktop\DAHF\OsEngine-master_github\OsEngine-master\project\OsEngine\OsData\OsDataSet.cs:line 763
   at OsEngine.OsData.OsDataSet.WorkerArea() in \\Mac\Home\Desktop\DAHF\OsEngine-master_github\OsEngine-master\project\OsEngine\OsData\OsDataSet.cs:line 519

**Comment by AlexWan** [comment]
поддержка на форуме: http://o-s-a.net/forum
для начинающих программистов которые проходят у нас обучение.
